import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { CalendarClock, CheckCircle2, Copy, ExternalLink, Globe2, Loader2, LockKeyhole, SearchCheck, Send, Settings2, ShieldCheck, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { useLanguage } from '@/contexts/LanguageContext';
import { cleanfixApi } from '@/lib/cleanfixApi';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

type Channel = 'facebook' | 'instagram' | 'x' | 'manual_share';
type Language = 'he' | 'en';
type GrowthSettings = { enabled: boolean; auto_generate: boolean; auto_publish: boolean; require_owner_approval: boolean; timezone: string; daily_time: string; daily_post_limit: number; lookahead_days: number; languages: Language[]; channels: Channel[]; content_pillars: string[]; default_cta: string; destination_url: string; approved_facts?: string; banned_phrases?: string; notification_email?: string };
type GrowthPost = { id: number; campaign_name: string; topic: string; channel: string; language: string; body: string; alt_text?: string; image_url?: string; destination_url: string; utm_url: string; status: string; content_version: number; approved_version?: number; scheduled_for?: string; approved_by?: string };
type GrowthSummary = { counts: Record<string, number>; automatic_publish_available: boolean; channel_status: { provider: string; state: string }[] };

const defaults: GrowthSettings = { enabled: false, auto_generate: true, auto_publish: false, require_owner_approval: true, timezone: 'Asia/Jerusalem', daily_time: '09:00', daily_post_limit: 1, lookahead_days: 7, languages: ['he', 'en'], channels: ['facebook', 'instagram'], content_pillars: ['helpful_tip', 'service_explainer', 'local_trust', 'before_you_book'], default_cta: 'Send details for an owner-reviewed quote', destination_url: 'https://cleanfixharish.co.il/quote' };

export default function GrowthCenter() {
  const { lang } = useLanguage();
  const he = lang === 'he';
  const [settings, setSettings] = useState<GrowthSettings>(defaults);
  const [posts, setPosts] = useState<GrowthPost[]>([]);
  const [summary, setSummary] = useState<GrowthSummary>({ counts: {}, automatic_publish_available: false, channel_status: [] });
  const [scheduleValues, setScheduleValues] = useState<Record<number, string>>({});
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    try {
      setError('');
      const [saved, postResult, summaryResult] = await Promise.all([cleanfixApi.getGrowthSettings(), cleanfixApi.listGrowthPosts(), cleanfixApi.getGrowthSummary()]);
      setSettings(saved); setPosts(postResult.items || []); setSummary(summaryResult);
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : (he ? 'מרכז הצמיחה אינו זמין.' : 'Growth Center is unavailable.'));
    } finally { setLoading(false); }
  }, [he]);
  useEffect(() => { void load(); }, [load]);

  const save = async () => { setBusy(true); try { setSettings(await cleanfixApi.updateGrowthSettings(settings)); toast.success(he ? 'הגדרות הצמיחה נשמרו' : 'Growth settings saved'); } catch (reason) { toast.error(message(reason, he ? 'השמירה נכשלה' : 'Save failed')); } finally { setBusy(false); } };
  const runExperts = async () => { setBusy(true); try { const run = await cleanfixApi.runDailyGrowthExperts(); toast.success(he ? `נוצרו ${run.drafts_created} טיוטות לבדיקה` : `${run.drafts_created} drafts created for review`); await load(); } catch (reason) { toast.error(message(reason, he ? 'הריצה נכשלה' : 'Daily run failed')); } finally { setBusy(false); } };
  const act = async (action: () => Promise<unknown>, success: string) => { setBusy(true); try { await action(); toast.success(success); await load(); } catch (reason) { toast.error(message(reason, he ? 'הפעולה נכשלה' : 'Action failed')); } finally { setBusy(false); } };
  const copyShareKit = async (post: GrowthPost) => { await navigator.clipboard.writeText(`${post.body}\n\n${post.utm_url}`); toast.success(he ? 'ערכת השיתוף הועתקה' : 'Share kit copied'); };

  if (loading) return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#174e57]" /></div>;
  return <div className="space-y-6">
    <div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#a87520]">SEO + organic growth</p><h1 className="mt-2 text-3xl text-[#173f46]">{he ? 'מרכז צמיחה' : 'Growth Center'}</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-[#625b53]">{he ? 'צוות מומחים יומי מכין אסטרטגיה, טקסטים ובדיקות מדיניות. רק הגרסה המדויקת שאושרה על ידי הבעלים יכולה להיכנס ללוח הפרסום.' : 'A daily expert workflow prepares strategy, native copy, and policy checks. Only the exact owner-approved version can enter the publishing calendar.'}</p></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Status icon={SearchCheck} label={he ? 'בדיקת SEO יומית' : 'Daily SEO audit'} value={he ? 'פעיל' : 'Active'} ready /><Status icon={Sparkles} label={he ? 'אוטומציית טיוטות' : 'Draft automation'} value={settings.enabled ? 'ON' : 'OFF'} ready={settings.enabled} /><Status icon={ShieldCheck} label={he ? 'ממתין לאישור' : 'Awaiting approval'} value={String(summary.counts.draft || 0)} ready /><Status icon={LockKeyhole} label={he ? 'פרסום API' : 'API publishing'} value={he ? 'טרם חובר' : 'Not connected'} ready={false} /></div>
    <Tabs defaultValue="today" dir={he ? 'rtl' : 'ltr'}>
      <TabsList className="h-auto flex-wrap bg-[#e9e3d9] p-1"><TabsTrigger value="today">{he ? 'היום' : 'Today'}</TabsTrigger><TabsTrigger value="calendar">{he ? 'לוח תוכן' : 'Calendar'}</TabsTrigger><TabsTrigger value="channels">{he ? 'ערוצים' : 'Channels'}</TabsTrigger><TabsTrigger value="settings">{he ? 'הגדרות' : 'Settings'}</TabsTrigger></TabsList>
      <TabsContent value="today" className="space-y-5">
        <Card className="border-[#d8d0c6] bg-[#fbf8f3]"><CardHeader><CardTitle className="flex items-center gap-2 text-xl text-[#173f46]"><Sparkles className="h-5 w-5 text-[#a87520]" />{he ? 'צוות המומחים היומי' : 'Daily expert team'}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-3">{[he ? 'אסטרטג: בוחר נושא, קהל וקריאה לפעולה' : 'Strategist: selects topic, audience, and CTA', he ? 'עורך דו־לשוני: יוצר עברית ואנגלית טבעיות' : 'Bilingual editor: creates native Hebrew and English', he ? 'בודק מדיניות: חוסם הבטחות וטענות לא מאומתות' : 'Policy reviewer: blocks promises and unsupported claims'].map((text) => <div key={text} className="rounded-xl border border-[#e5ddd3] bg-white p-4 text-sm leading-6 text-[#4b5b5d]">{text}</div>)}</div><Button onClick={runExperts} disabled={busy || !settings.enabled} className="mt-4 min-h-11 bg-[#174e57]"><Sparkles className="me-2 h-4 w-4" />{he ? 'הפעלת המומחים עכשיו' : 'Run experts now'}</Button>{!settings.enabled && <p className="mt-2 text-xs text-[#786f65]">{he ? 'הפעילו את המערכת בלשונית הגדרות.' : 'Enable the system in Settings first.'}</p>}</CardContent></Card>
        <div className="grid gap-4 xl:grid-cols-2">{posts.filter((post) => post.status !== 'published').slice(0, 12).map((post) => <PostCard key={post.id} post={post} he={he} busy={busy} scheduleValue={scheduleValues[post.id] || ''} onScheduleValue={(value) => setScheduleValues((current) => ({ ...current, [post.id]: value }))} onCopy={() => copyShareKit(post)} onApprove={() => act(() => cleanfixApi.approveGrowthPost(post.id), he ? 'הטיוטה אושרה' : 'Draft approved')} onSchedule={() => act(() => cleanfixApi.scheduleGrowthPost(post.id, scheduleValues[post.id]), he ? 'נוסף ללוח' : 'Added to calendar')} onPublished={() => act(() => cleanfixApi.markGrowthPostPublished(post.id), he ? 'סומן כפורסם' : 'Marked published')} />)}</div>
        {!posts.length && <Empty text={he ? 'עדיין אין טיוטות. שמרו הגדרות והפעילו את צוות המומחים.' : 'No drafts yet. Save settings and run the expert team.'} />}
      </TabsContent>
      <TabsContent value="calendar"><div className="grid gap-4 lg:grid-cols-2">{posts.filter((post) => ['scheduled', 'published'].includes(post.status)).map((post) => <Card key={post.id} className="border-[#d8d0c6] bg-[#fbf8f3]"><CardContent className="p-5"><div className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-[#a87520]"/><strong>{post.channel} · {post.language.toUpperCase()}</strong><StateBadge state={post.status}/></div><p className="mt-3 text-sm leading-6 text-[#4b5b5d]">{post.body}</p><p className="mt-3 text-xs text-[#786f65]" dir="ltr">{post.scheduled_for ? new Date(post.scheduled_for).toLocaleString(he ? 'he-IL' : 'en-IL', { timeZone: 'Asia/Jerusalem' }) : 'Manual publication'}</p></CardContent></Card>)}</div>{!posts.some((post) => ['scheduled', 'published'].includes(post.status)) && <Empty text={he ? 'לוח התוכן עדיין ריק.' : 'The content calendar is empty.'} />}</TabsContent>
      <TabsContent value="channels"><Card className="border-[#d8d0c6] bg-[#fbf8f3]"><CardHeader><CardTitle>{he ? 'ערוצי הפצה' : 'Distribution channels'}</CardTitle></CardHeader><CardContent className="space-y-3">{summary.channel_status.map((channel) => <div key={channel.provider} className="flex items-center gap-3 rounded-xl border border-[#e5ddd3] bg-white p-4"><Send className="h-5 w-5 text-[#174e57]"/><span className="flex-1 font-semibold capitalize">{channel.provider.replace('_', ' ')}</span><Badge className={channel.state === 'ready' ? 'bg-[#dceadf] text-[#2e6840]' : 'bg-[#eee4d4] text-[#765d38]'}>{channel.state.split('_').join(' ')}</Badge></div>)}<p className="text-xs leading-5 text-[#786f65]">{he ? 'Facebook ו-Instagram יחוברו דרך Meta API הרשמי. קבוצות, פורומים וקבוצות WhatsApp נשארים ערכת שיתוף ידנית.' : 'Facebook and Instagram will connect through the official Meta API. Groups, forums, and WhatsApp groups remain manual share kits.'}</p></CardContent></Card></TabsContent>
      <TabsContent value="settings"><SettingsPanel settings={settings} setSettings={setSettings} he={he} busy={busy} onSave={save} /></TabsContent>
    </Tabs>
  </div>;
}

function SettingsPanel({ settings, setSettings, he, busy, onSave }: { settings: GrowthSettings; setSettings: (value: GrowthSettings) => void; he: boolean; busy: boolean; onSave: () => void }) {
  const toggleList = (field: 'languages' | 'channels', value: string) => { const current = settings[field] as string[]; const next = current.includes(value) ? current.filter((item) => item !== value) : [...current, value]; if (next.length) setSettings({ ...settings, [field]: next } as GrowthSettings); };
  return <Card className="border-[#d8d0c6] bg-[#fbf8f3]"><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-[#a87520]"/>{he ? 'הגדרות אוטומציה' : 'Automation settings'}</CardTitle></CardHeader><CardContent className="space-y-5">
    <label className="flex items-center gap-3 rounded-xl border border-[#e5ddd3] bg-white p-4"><input type="checkbox" checked={settings.enabled} onChange={(event) => setSettings({ ...settings, enabled: event.target.checked })}/><span><strong>{he ? 'הפעלת יצירת טיוטות יומית' : 'Enable daily draft generation'}</strong><small className="block text-[#786f65]">{he ? 'לא מפרסם החוצה ללא אישור.' : 'Does not publish externally without approval.'}</small></span></label>
    <div className="grid gap-4 md:grid-cols-3"><Field label={he ? 'שעה יומית' : 'Daily time'}><Input type="time" value={settings.daily_time} onChange={(event) => setSettings({ ...settings, daily_time: event.target.value })}/></Field><Field label={he ? 'מספר פוסטים ביום' : 'Posts per day'}><Input type="number" min={1} max={5} value={settings.daily_post_limit} onChange={(event) => setSettings({ ...settings, daily_post_limit: Number(event.target.value) })}/></Field><Field label={he ? 'ימי תכנון קדימה' : 'Lookahead days'}><Input type="number" min={1} max={30} value={settings.lookahead_days} onChange={(event) => setSettings({ ...settings, lookahead_days: Number(event.target.value) })}/></Field></div>
    <div className="grid gap-4 md:grid-cols-2"><Field label={he ? 'שפות' : 'Languages'}><Choice value="he" label="עברית" active={settings.languages.includes('he')} onClick={() => toggleList('languages', 'he')}/><Choice value="en" label="English" active={settings.languages.includes('en')} onClick={() => toggleList('languages', 'en')}/></Field><Field label={he ? 'ערוצים לטיוטות' : 'Draft channels'}>{(['facebook', 'instagram', 'x', 'manual_share'] as const).map((channel) => <Choice key={channel} value={channel} label={channel.replace('_', ' ')} active={settings.channels.includes(channel)} onClick={() => toggleList('channels', channel)}/>)}</Field></div>
    <Field label={he ? 'קריאה לפעולה קבועה' : 'Default call to action'}><Input value={settings.default_cta} onChange={(event) => setSettings({ ...settings, default_cta: event.target.value })}/></Field><Field label={he ? 'דף נחיתה' : 'Landing page'}><Input dir="ltr" value={settings.destination_url} onChange={(event) => setSettings({ ...settings, destination_url: event.target.value })}/></Field>
    <div className="grid gap-4 md:grid-cols-2"><Field label={he ? 'עובדות מאושרות בלבד' : 'Approved facts only'}><Textarea rows={5} value={settings.approved_facts || ''} onChange={(event) => setSettings({ ...settings, approved_facts: event.target.value })}/></Field><Field label={he ? 'ביטויים אסורים' : 'Banned phrases'}><Textarea rows={5} value={settings.banned_phrases || ''} onChange={(event) => setSettings({ ...settings, banned_phrases: event.target.value })}/></Field></div>
    <Field label={he ? 'אימייל להתראות' : 'Notification email'}><Input type="email" dir="ltr" value={settings.notification_email || ''} onChange={(event) => setSettings({ ...settings, notification_email: event.target.value })}/></Field>
    <div className="rounded-xl border border-[#e6d5b8] bg-[#fff8e9] p-4 text-sm text-[#765d38]"><LockKeyhole className="me-2 inline h-4 w-4"/>{he ? 'אישור בעלים חובה ופרסום אוטומטי נשאר כבוי עד חיבור ובדיקת API רשמי.' : 'Owner approval is mandatory and automatic publishing stays off until an official API connection passes verification.'}</div><Button onClick={onSave} disabled={busy} className="min-h-11 bg-[#174e57]">{busy && <Loader2 className="me-2 h-4 w-4 animate-spin"/>}{he ? 'שמירת כל ההגדרות' : 'Save all settings'}</Button>
  </CardContent></Card>;
}

function PostCard({ post, he, busy, scheduleValue, onScheduleValue, onCopy, onApprove, onSchedule, onPublished }: { post: GrowthPost; he: boolean; busy: boolean; scheduleValue: string; onScheduleValue: (value: string) => void; onCopy: () => void; onApprove: () => void; onSchedule: () => void; onPublished: () => void }) { const approved = post.approved_version === post.content_version; return <Card className="border-[#d8d0c6] bg-[#fbf8f3]"><CardHeader><CardTitle className="flex flex-wrap items-center gap-2 text-lg"><span className="capitalize">{post.channel}</span><Badge variant="outline">{post.language.toUpperCase()}</Badge><StateBadge state={post.status}/></CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm leading-6 text-[#3f5052]">{post.body}</p><a href={post.utm_url} target="_blank" rel="noreferrer" className="mt-3 block break-all text-xs text-[#174e57] underline" dir="ltr">{post.utm_url}<ExternalLink className="ms-1 inline h-3 w-3"/></a><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={onCopy}><Copy className="me-2 h-4 w-4"/>{he ? 'העתקת ערכה' : 'Copy kit'}</Button>{!approved && <Button disabled={busy} onClick={onApprove} className="bg-[#174e57]"><CheckCircle2 className="me-2 h-4 w-4"/>{he ? 'אישור בעלים' : 'Owner approve'}</Button>}{approved && post.status !== 'published' && <Button variant="outline" disabled={busy} onClick={onPublished}>{he ? 'סימון כפורסם ידנית' : 'Mark manually posted'}</Button>}</div>{approved && post.status !== 'published' && <div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input type="datetime-local" value={scheduleValue} onChange={(event) => onScheduleValue(event.target.value)}/><Button disabled={!scheduleValue || busy} onClick={onSchedule}><CalendarClock className="me-2 h-4 w-4"/>{he ? 'הוספה ללוח' : 'Schedule'}</Button></div>}</CardContent></Card>; }
function Status({ icon: Icon, label, value, ready }: { icon: typeof Globe2; label: string; value: string; ready: boolean }) { return <Card className="border-[#d8d0c6] bg-[#fbf8f3]"><CardContent className="flex items-center gap-3 p-4"><span className="rounded-xl bg-[#dde9e7] p-2"><Icon className="h-5 w-5 text-[#174e57]"/></span><div><p className="text-xs text-[#786f65]">{label}</p><p className="mt-1 font-bold text-[#173f46]">{value}</p></div><Badge className={`ms-auto ${ready ? 'bg-[#dceadf] text-[#2e6840]' : 'bg-[#eee4d4] text-[#765d38]'}`}>{ready ? 'ON' : 'OFF'}</Badge></CardContent></Card>; }
function StateBadge({ state }: { state: string }) { const good = ['approved', 'scheduled', 'published'].includes(state); return <Badge className={`ms-auto ${good ? 'bg-[#dceadf] text-[#2e6840]' : 'bg-[#eee4d4] text-[#765d38]'}`}>{state}</Badge>; }
function Empty({ text }: { text: string }) { return <div className="mt-5 rounded-xl border border-dashed border-[#cfc5b9] bg-[#fbf8f3] p-8 text-center text-sm text-[#786f65]">{text}</div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2 text-sm font-semibold text-[#324346]"><span>{label}</span><div className="flex flex-wrap gap-2">{children}</div></label>; }
function Choice({ value, label, active, onClick }: { value: string; label: string; active: boolean; onClick: () => void }) { return <button type="button" data-value={value} onClick={onClick} className={`rounded-lg border px-3 py-2 text-sm capitalize ${active ? 'border-[#174e57] bg-[#dde9e7] text-[#174e57]' : 'border-[#d8d0c6] bg-white text-[#786f65]'}`}>{label}</button>; }
function message(reason: unknown, fallback: string) { return reason instanceof Error ? reason.message : fallback; }
