import { useEffect, useMemo, useState } from 'react';
import { Check, Copy, Download, Palette, Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { useLanguage } from '@/contexts/LanguageContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { cleanfixApi } from '@/lib/cleanfixApi';
import {
  applyThemeVariables,
  generateLocalHarmony,
  normalizeHex,
  paletteToTheme,
  readableForeground,
  THEME_PRESETS_KEY,
  themeCssExport,
  themeTailwindExport,
  type HarmonyRule,
  type ThemeColors,
  type ThemePreset,
} from '@/lib/themeStudio';

type Props = {
  value: ThemeColors;
  onChange: (colors: ThemeColors) => void;
};

function loadPresets(): ThemePreset[] {
  try {
    const parsed = JSON.parse(localStorage.getItem(THEME_PRESETS_KEY) || '[]');
    return Array.isArray(parsed) ? parsed.filter((item) => item?.id && item?.colors) : [];
  } catch {
    return [];
  }
}

async function copyExport(text: string, success: string) {
  await navigator.clipboard.writeText(text);
  toast.success(success);
}

export default function ThemeStudio({ value, onChange }: Props) {
  const { lang } = useLanguage();
  const he = lang === 'he';
  const [baseColor, setBaseColor] = useState(normalizeHex(value.primary_color));
  const [harmony, setHarmony] = useState<HarmonyRule>('complementary');
  const [palette, setPalette] = useState<string[]>([value.primary_color, value.accent_color, value.surface_color]);
  const [source, setSource] = useState<'current' | 'botoi' | 'local'>('current');
  const [generating, setGenerating] = useState(false);
  const [presetName, setPresetName] = useState('');
  const [presets, setPresets] = useState<ThemePreset[]>(loadPresets);

  useEffect(() => {
    applyThemeVariables(value);
  }, [value]);

  const contrastPairs = useMemo(() => [
    { color: value.primary_color, foreground: readableForeground(value.primary_color) },
    { color: value.accent_color, foreground: readableForeground(value.accent_color) },
  ], [value]);

  const generate = async () => {
    const normalizedBase = normalizeHex(baseColor);
    setGenerating(true);
    try {
      const response = await cleanfixApi.generateThemePalette({ color: normalizedBase, type: harmony });
      const nextPalette = Array.isArray(response.colors) ? response.colors : [];
      if (!nextPalette.length) throw new Error('No palette');
      setPalette(nextPalette);
      setSource('botoi');
      onChange(paletteToTheme(normalizedBase, nextPalette));
      toast.success(he ? 'הפלטה נוצרה באמצעות Botoi.' : 'Palette generated by Botoi.');
    } catch {
      const nextPalette = generateLocalHarmony(normalizedBase, harmony);
      setPalette(nextPalette);
      setSource('local');
      onChange(paletteToTheme(normalizedBase, nextPalette));
      toast.info(he ? 'Botoi לא היה זמין. הופעלה יצירה מקומית בטוחה.' : 'Botoi was unavailable. Safe local generation was used.');
    } finally {
      setGenerating(false);
    }
  };

  const updateColor = (key: keyof ThemeColors, color: string) => {
    const next = { ...value, [key]: normalizeHex(color, value[key]) };
    onChange(next);
  };

  const persistPresets = (next: ThemePreset[]) => {
    setPresets(next);
    localStorage.setItem(THEME_PRESETS_KEY, JSON.stringify(next));
  };

  const savePreset = () => {
    const name = presetName.trim() || `${he ? 'פלטה' : 'Palette'} ${presets.length + 1}`;
    const preset: ThemePreset = {
      id: globalThis.crypto?.randomUUID?.() || `${Date.now()}`,
      name,
      createdAt: new Date().toISOString(),
      baseColor,
      harmony,
      colors: value,
    };
    persistPresets([preset, ...presets].slice(0, 24));
    setPresetName('');
    toast.success(he ? 'הפלטה נשמרה בדפדפן הזה.' : 'Preset saved in this browser.');
  };

  const labels = {
    title: he ? 'סטודיו צבע חי' : 'Live theme studio',
    intro: he ? 'בחרו צבע בסיס והרמוניה. השינוי מוצג מיד; הפרסום מתבצע רק בכפתור הפרסום שמתחת.' : 'Choose a base color and harmony. Changes preview instantly; publishing still happens with the button below.',
    base: he ? 'צבע בסיס' : 'Base color',
    harmony: he ? 'כלל הרמוניה' : 'Harmony rule',
    generate: he ? 'יצירת פלטה' : 'Generate palette',
    preset: he ? 'שם הפלטה' : 'Preset name',
  };

  return (
    <section className="mt-1 rounded-2xl border border-[#CFC5B9] bg-[#FBF8F3] p-4 sm:p-5" aria-labelledby="theme-studio-title">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="flex items-center gap-2"><Palette className="h-5 w-5 text-[#805416]" /><h3 id="theme-studio-title" className="font-sans text-base font-semibold text-[#173F46]">{labels.title}</h3></div>
          <p className="mt-1 max-w-2xl text-xs leading-5 text-[#625B53]">{labels.intro}</p>
        </div>
        <span className="rounded-full border border-[#B8842F]/35 bg-white px-3 py-1 text-xs text-[#625B53]" aria-live="polite">
          {source === 'botoi' ? 'Botoi API' : source === 'local' ? (he ? 'גיבוי מקומי' : 'Local fallback') : (he ? 'פלטה נוכחית' : 'Current palette')}
        </span>
      </div>

      <div className="mt-5 grid gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end">
        <Label className="text-xs text-[#625B53]">{labels.base}<div className="mt-2 flex min-h-11 items-center gap-2 rounded-xl border bg-white p-2"><input type="color" value={baseColor} onChange={(event) => setBaseColor(event.target.value.toUpperCase())} className="h-9 w-12 cursor-pointer" aria-label={labels.base} /><Input value={baseColor} onChange={(event) => setBaseColor(event.target.value.toUpperCase())} onBlur={() => setBaseColor(normalizeHex(baseColor))} className="h-9 border-0 p-0 font-mono shadow-none" maxLength={7} dir="ltr" /></div></Label>
        <div><Label className="text-xs text-[#625B53]">{labels.harmony}</Label><Select value={harmony} onValueChange={(value: HarmonyRule) => setHarmony(value)}><SelectTrigger className="mt-2 min-h-11 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="complementary">{he ? 'משלימה' : 'Complementary'}</SelectItem><SelectItem value="analogous">{he ? 'אנלוגית' : 'Analogous'}</SelectItem><SelectItem value="triadic">{he ? 'משולשת' : 'Triadic'}</SelectItem></SelectContent></Select></div>
        <Button type="button" onClick={generate} disabled={generating} className="min-h-11 bg-[#173F46] text-white hover:bg-[#102E38]"><RefreshCw className={`me-2 h-4 w-4 ${generating ? 'animate-spin' : ''}`} />{labels.generate}</Button>
      </div>

      <div className="mt-5" role="group" aria-label={he ? 'צבעי הפלטה שנוצרה' : 'Generated palette colors'}>
        <div className="grid grid-cols-3 gap-2 sm:grid-cols-5">{palette.map((color, index) => <button key={`${color}-${index}`} type="button" onClick={() => { setBaseColor(color); updateColor('primary_color', color); }} className="min-h-16 overflow-hidden rounded-xl border border-black/10 text-xs font-semibold shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2" style={{ backgroundColor: color, color: readableForeground(color) }} aria-label={`${he ? 'החלת צבע' : 'Use color'} ${color}`}>{color}</button>)}</div>
      </div>

      <div className="mt-5 grid gap-3 sm:grid-cols-3">{([
        [he ? 'ראשי' : 'Primary', 'primary_color'],
        [he ? 'הדגשה' : 'Accent', 'accent_color'],
        [he ? 'רקע' : 'Surface', 'surface_color'],
      ] as const).map(([label, key]) => <Label key={key} className="text-xs text-[#625B53]">{label}<div className="mt-2 flex min-h-11 items-center gap-2 rounded-xl border bg-white p-2"><input type="color" value={value[key]} onChange={(event) => updateColor(key, event.target.value)} className="h-9 w-12 cursor-pointer" aria-label={label} /><span className="font-mono">{value[key]}</span></div></Label>)}</div>

      <div className="mt-5 overflow-hidden rounded-2xl border" style={{ backgroundColor: value.surface_color }}>
        <div className="grid gap-4 p-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em]" style={{ color: value.accent_color }}>{he ? 'תצוגה חיה' : 'Live preview'}</p><h4 className="mt-2 font-sans text-xl font-bold" style={{ color: value.primary_color }}>{he ? 'שירות מקומי, ברור ואמין' : 'Local service, clear and trusted'}</h4><p className="mt-2 text-sm text-[#625B53]">{he ? 'הצבעים משתנים מיד בכל רכיבי המערכת שמשתמשים באסימוני העיצוב.' : 'Colors change instantly across components that use the shared design tokens.'}</p></div><button type="button" className="min-h-11 rounded-xl px-5 text-sm font-semibold" style={{ backgroundColor: value.primary_color, color: readableForeground(value.primary_color) }}>{he ? 'קבלו הצעה' : 'Get a quote'}</button></div>
        <div className="grid grid-cols-2">{contrastPairs.map(({ color, foreground }) => <div key={color} className="flex min-h-12 items-center justify-center gap-2 text-xs font-semibold" style={{ backgroundColor: color, color: foreground }}><Check className="h-4 w-4" />{he ? 'טקסט קריא' : 'Readable text'}</div>)}</div>
      </div>

      <div className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto_auto] lg:items-end"><Label className="text-xs text-[#625B53]">{labels.preset}<Input value={presetName} onChange={(event) => setPresetName(event.target.value)} className="mt-2 min-h-11 bg-white" placeholder={he ? 'לדוגמה: זהב רגוע' : 'For example: Calm gold'} /></Label><Button type="button" variant="outline" onClick={savePreset} className="min-h-11"><Save className="me-2 h-4 w-4" />{he ? 'שמירת פלטה' : 'Save preset'}</Button><div className="flex gap-2"><Button type="button" variant="outline" onClick={() => copyExport(themeCssExport(value), he ? 'CSS הועתק.' : 'CSS copied.')} className="min-h-11 flex-1"><Copy className="me-2 h-4 w-4" />CSS</Button><Button type="button" variant="outline" onClick={() => copyExport(themeTailwindExport(value), he ? 'Tailwind הועתק.' : 'Tailwind copied.')} className="min-h-11 flex-1"><Download className="me-2 h-4 w-4" />Tailwind</Button></div></div>

      {!!presets.length && <div className="mt-5 border-t pt-4"><p className="text-xs font-semibold text-[#625B53]">{he ? 'פלטות שמורות בדפדפן הזה' : 'Presets saved in this browser'}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{presets.map((preset) => <div key={preset.id} className="flex items-center gap-2 rounded-xl border bg-white p-2"><button type="button" onClick={() => { setBaseColor(preset.baseColor); setHarmony(preset.harmony); setPalette(Object.values(preset.colors)); onChange(preset.colors); }} className="flex min-h-11 min-w-0 flex-1 items-center gap-3 rounded-lg px-2 text-start hover:bg-[#F7F2EA]"><span className="flex shrink-0">{Object.values(preset.colors).map((color) => <span key={color} className="h-7 w-4 first:rounded-s-md last:rounded-e-md" style={{ backgroundColor: color }} />)}</span><span className="truncate text-sm font-medium">{preset.name}</span></button><Button type="button" size="icon" variant="ghost" className="h-11 w-11" aria-label={`${he ? 'מחיקת' : 'Delete'} ${preset.name}`} onClick={() => persistPresets(presets.filter((item) => item.id !== preset.id))}><Trash2 className="h-4 w-4" /></Button></div>)}</div></div>}
    </section>
  );
}
