import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Card, CardContent } from '@/components/ui/card';

export default function AccessibilityPage() {
  return <div className="min-h-screen bg-[#F3EFE7] text-[#243538]"><Header/><main id="main-content" className="mx-auto max-w-3xl px-4 py-12 sm:py-16"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#9A7548]">Accessibility</p><h1 className="mt-3 text-4xl text-[#173F46]">A service that should be easy to use.</h1><p className="mt-5 text-base leading-8 text-[#6F675F]">CleanFixHarish is working toward an accessible digital experience aligned with Israeli Standard 5568 and WCAG 2.1 Level AA. This page does not claim formal certification; independent review remains part of launch quality assurance.</p><Card className="mt-8 border-[#D8D0C6] bg-[#FBF8F3]"><CardContent className="space-y-7 p-6 sm:p-8"><Section title="Tools available now"><ul><li>Keyboard-friendly navigation and visible focus states</li><li>English and Hebrew direction support</li><li>Responsive text and mobile layouts</li><li>An accessibility menu for text size, contrast, link visibility, and reduced motion</li><li>Text labels for key actions and meaningful images</li></ul></Section><Section title="Need assistance?"><p>If any page, form, or service is difficult to use, contact us and we will provide the information or service through an accessible alternative.</p><p className="mt-3"><a href="tel:+972508275505">050-827-5505</a><br/><a href="mailto:info@cleanfixharish.co.il">info@cleanfixharish.co.il</a></p></Section><Section title="Ongoing improvement"><p>Accessibility is reviewed as the site changes. Issues are prioritized alongside security and core service functionality.</p></Section></CardContent></Card></main><Footer/></div>;
}

function Section({title,children}:{title:string;children:React.ReactNode}) { return <section><h2 className="font-sans text-lg font-semibold text-[#173F46]">{title}</h2><div className="mt-2 text-sm leading-7 text-[#625B53] [&_a]:font-medium [&_a]:text-[#174E57] [&_a]:underline [&_ul]:list-disc [&_ul]:space-y-1 [&_ul]:pl-5">{children}</div></section>; }
