import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Download, FileCheck2, MessageSquareLock, ShieldCheck, WalletCards } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import PublicSite from '@/components/PublicSite';
import { useLanguage } from '@/contexts/LanguageContext';
import { Button } from '@/components/ui/button';

export default function HowWeWorkPage() {
  const { lang } = useLanguage();
  const he = lang === 'he';
  const steps = he
    ? ['אתם שולחים בקשה ותמונות', 'אנחנו מסווגים סיכון ומגדירים היקף', 'אתם מקבלים מחיר ותנאים בכתב', 'CleanFix משבצת בעל מקצוע מאושר', 'העבודה מתועדת ונבדקת', 'CleanFix סוגרת איכות ומשלמת לבעל המקצוע']
    : ['You send a request and photos', 'We classify risk and define the scope', 'You receive the price and terms in writing', 'CleanFix assigns an approved service partner', 'The work is documented and reviewed', 'CleanFix closes quality and pays the provider'];
  const downloads = he
    ? [['/legal/customer-service-terms-he.pdf', 'תנאי שירות ללקוח'], ['/legal/privacy-notice-he.pdf', 'הודעת פרטיות'], ['/legal/provider-principles-he.pdf', 'עקרונות התקשרות לבעלי מקצוע']]
    : [['/legal/customer-service-terms-en.pdf', 'Customer service terms'], ['/legal/privacy-notice-en.pdf', 'Privacy notice'], ['/legal/provider-principles-en.pdf', 'Service partner principles']];
  return <PublicSite><Header /><main className="flex-1">
    <section className="cf-navy-panel py-[55px] md:py-[89px]"><div className="cf-shell mx-auto max-w-4xl text-center"><p className="cf-eyebrow">{he ? 'אחריות אחת, תהליך אחד' : 'One accountable process'}</p><div className="cf-gold-rule mx-auto" /><h1 className="text-4xl text-[#f7f2ea] md:text-6xl">{he ? 'אתם מזמינים את CleanFixHarish.' : 'You hire CleanFixHarish.'}</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-[#e8d8be]">{he ? 'אנחנו מגדירים את ההיקף, מנהלים את בעל המקצוע, שולטים בתשלום ובשינויים, בודקים את האיכות ונשארים הכתובת לפתרון.' : 'We define the scope, manage the service partner, control payment and changes, review quality and remain the contact for resolution.'}</p></div></section>
    <section className="bg-[#f7f2ea] py-[55px] md:py-[89px]"><div className="cf-shell grid gap-8 lg:grid-cols-[1fr_1.618fr]"><div><p className="cf-eyebrow">{he ? 'הדרך' : 'The journey'}</p><div className="cf-gold-rule" /><h2 className="text-3xl text-[#102e38] md:text-5xl">{he ? 'כל שלב משאיר עקבה ברורה.' : 'Every step leaves a clear record.'}</h2><p className="mt-4 leading-7 text-[#617074]">{he ? 'אין תוספות בעל פה, אין החלפת בעל מקצוע שקטה ואין תשלום פרטי. שינוי מהותי עוצר את העבודה הרלוונטית עד לאישור מחיר והיקף מעודכנים.' : 'No verbal extras, silent provider substitutions or private payments. A material change pauses affected work until an updated scope and price are approved.'}</p></div><ol className="space-y-3">{steps.map((step, index) => <li key={step} className="flex items-center gap-4 rounded-2xl border border-[#d8d0c6] bg-[#fbf8f3] p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#102e38] font-bold text-[#f0c96f]">{index + 1}</span><span className="font-semibold text-[#324346]">{step}</span><CheckCircle2 className="ms-auto h-5 w-5 text-[#4f7b57]" /></li>)}</ol></div></section>
    <section className="bg-[#fbf8f3] py-[55px]"><div className="cf-shell grid gap-5 md:grid-cols-3">{[
      [MessageSquareLock, he ? 'קשר דרך CleanFix' : 'Contact through CleanFix', he ? 'בעל המקצוע מזוהה בבטחה, אך מספרו הפרטי, הצעתו והתשלום נשארים מחוץ למסע.' : 'The provider is safely identified, while personal numbers, private quotes and payment stay outside the journey.'],
      [WalletCards, he ? 'תשלום נשלט' : 'Controlled payment', he ? 'הלקוח משלם ל-CleanFix ובעל המקצוע מקבל תשלום מוסכם לאחר סגירת איכות.' : 'The customer pays CleanFix and the provider receives the agreed payout after quality close.'],
      [ShieldCheck, he ? 'פתרון מתועד' : 'Documented resolution', he ? 'בעיה נבדקת מול ההיקף והתיעוד ויכולה להוביל לתיקון, החלפה, זיכוי או החזר יחסי.' : 'An issue is reviewed against scope and evidence and may lead to rework, replacement, credit or proportional refund.'],
    ].map(([Icon, title, copy]) => <article key={String(title)} className="rounded-[21px] border border-[#d8d0c6] bg-white p-6"><Icon className="h-7 w-7 text-[#a87520]" /><h2 className="mt-4 text-2xl text-[#102e38]">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-[#617074]">{String(copy)}</p></article>)}</div></section>
    <section className="cf-ivory-orbit py-[55px] md:py-[89px]"><div className="cf-shell"><div className="mx-auto max-w-3xl text-center"><FileCheck2 className="mx-auto h-9 w-9 text-[#a87520]" /><h2 className="mt-4 text-3xl text-[#102e38] md:text-5xl">{he ? 'הכללים כתובים ונגישים.' : 'The rules are written and accessible.'}</h2><p className="mt-4 text-sm leading-6 text-[#617074]">{he ? 'המסמכים הבאים הם טיוטות תפעוליות עד לאישור עורך דין ישראלי. הגרסה המחייבת תציג תאריך תחילה ומספר גרסה.' : 'The documents below are operational drafts until approved by Israeli counsel. A binding version will show an effective date and version number.'}</p></div><div className="mx-auto mt-8 grid max-w-4xl gap-3 md:grid-cols-3">{downloads.map(([href, label]) => <a key={href} href={href} download className="flex min-h-14 items-center justify-center gap-2 rounded-xl border border-[#b8842f]/45 bg-[#fbf8f3] px-4 font-semibold text-[#174e57] shadow-sm hover:border-[#b8842f]"><Download className="h-4 w-4" />{label}</a>)}</div><div className="mt-9 text-center"><Button asChild className="min-h-12 bg-[#102e38]"><Link to="/quote">{he ? 'שלחו בקשת שירות' : 'Send a service request'}<ArrowRight className="ms-2 h-4 w-4" /></Link></Button></div></div></section>
  </main><Footer /></PublicSite>;
}
